XPATH_VALOR_PRODUTO_INPUT = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[2]/div/div/div/input
XPATH_VALOR_DESCONTO_LABEL = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[3]/div/div/label
XPATH_VALOR_DESCONTO_INPUT = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[3]/div/div/div/input
XPATH_VALOR_FRETE_LABEL = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[5]/div/div[1]/label
XPATH_VALOR_FRETE_INPUT = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[5]/div/div[1]/div/input
XPATH_OUTRAS_DESPESAS_LABEL = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[6]/div/div[1]/label
XPATH_OUTRAS_DESPESAS_INPUT = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[6]/div/div[1]/div/input
XPATH_VALOR_SEGURO_LABEL = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[7]/div/div/label
XPATH_VALOR_SEGURO_INPUT = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[7]/div/div/div/input
XPATH_BASE_CALCULO_ICMS_LABEL = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[8]/div/div/label
XPATH_BASE_CALCULO_ICMS_INPUT = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[8]/div/div/div/input
XPATH_ALIQUOTA_ICMS_LABEL = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[10]/div/div/label
XPATH_ALIQUOTA_ICMS_INPUT = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[10]/div/div/div/input
XPATH_VALOR_ICMS_LABEL = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[11]/div/div/label
XPATH_VALOR_ICMS_INPUT = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[11]/div/div/div/input
XPATH_MESSAGEM_VALOR_INFORMADO = //*[@id="root"]/div[2]/div[6]/div/div[2]/p
XPATH_BASE_CALCULO_IPI_LABEL = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[12]/div/div/label
XPATH_BASE_CALCULO_IPI_INPUT = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[12]/div/div/div/input
XPATH_ALIQUOTA_IPI_LABEL = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[13]/div/div/label
XPATH_ALIQUOTA_IPI_INPUT = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[13]/div/div/div/input
XPATH_VALOR_IPI_LABEL = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[14]/div/div/label
XPATH_VALOR_IPI_INPUT = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[14]/div/div/div/input
XPATH_BASE_CALCULO_ST_LABEL = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[15]/div/div/label
XPATH_BASE_CALCULO_ST_INPUT = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[15]/div/div/div/input
XPATH_VALOR_ST_LABEL = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[16]/div/div/label
XPATH_VALOR_ST_INPUT = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[16]/div/div/div/input
XPATH_EDITA_DIFAL_LABEL = //*[@id="root"]/div[2]/div[5]/div/div[2]/form/div[1]/div[19]/div/label/span[1]/span[1]
XPATH_CST_ICMS_LABEL = //*[@id="root"]/div[2]/div[6]/div/div[2]/form/div[1]/div[1]/div/div/label
XPATH_CST_ICMS_INPUT = //*[@id="root"]/div[2]/div[6]/div/div[2]/form/div[1]/div[1]/div/div/div/input
XPATH_CFOP_LABEL = //*[@id="root"]/div[2]/div[6]/div/div[2]/form/div[1]/div[2]/div/div[1]/label
XPATH_CFOP_INPUT = //*[@id="root"]/div[2]/div[6]/div/div[2]/form/div[1]/div[2]/div/div[1]/div/input
XPATH_TAB_FORM = //*[@id="root"]/div[2]/div[5]/div/div[2]/form
XPATH_TAB_FORM_TWO = //*[@id="root"]/div[2]/div[6]/div/div[2]/form
